#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           8
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# bidirectional clipboard
vmware-user-suid-wrapper &

# fix java error
wmname LG3D &
export _JAVA_AWT_WM_NONREPARENTING=1

# wallpaper
feh --bg-fill /home/li4n/Pictures/wallpaper.jpg &

# polybar
if pgrep -x "polybar" > /dev/null
then
    killall -q polybar && sleep 1
fi
polybar &

# picom
if pgrep -x "picom" > /dev/null
then
    killall -q picom && sleep 1
fi
picom --config /home/li4n/.config/picom/picom.conf --daemon &
